apiVersion: v1
kind: Service
metadata:
  name: music-recommender-service
spec:
  type: NodePort
  selector:
    app: music-recommender
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
